### ISSUE TITLE
Public secret

### ISSUE THREAD

**Issue by ozgurozbek** [joeloverbeck/neural-narrative#1]
I've seen your recent blog post, and read through. Curious, checked the repository. Fun and very extensive project!

You should change and hide [this](https://github.com/joeloverbeck/neural-narrative/blob/main/RUNPOD_SECRET_KEY.txt) or `gitignore`. See [GitHub's post](https://docs.github.com/en/actions/security-for-github-actions/security-guides/using-secrets-in-github-actions) for actions as well.

**Comment by joeloverbeck** [comment]
Thank you for checking the repository out. I should probably write a proper README one of these days if people are going to visit.

**Comment by ozgurozbek** [comment]
Honestly the blogpost was a very good read, maybe a summary would work, and a how-to-run 😄 Just in case, make sure you've changed your key since it is [visible in your commit history](https://github.com/joeloverbeck/neural-narrative/commit/7af2222e12213bebe6021ecba65b6273b08b56e8) as well! Feel free to mark as closed if so 😃

**Comment by joeloverbeck** [comment]
Yes, I've yet to work on writing a README because the project is nowhere
close to being that stable. As of the latest commit, it can't even do the
things it did recently, as I'm in the process of reworking the hierarchy of
places involved in a story.

I did notice the RunPod key thing, yes, but thank you for pointing it out.
Thankfully they aren't hard to change.
